version: 2.1
orbs:
  gcloud: circleci/gcp-cli@1.3.0

jobs:
  deploy:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - gcloud/install
      - gcloud/initialize
      - run:
          name: Copy to gcs
          command: |
            if [ $CIRCLE_BRANCH=master ];then CHANNEL=stable; else CHANNEL=staging; fi
            GCS_PATH=gs://widgets.risevision.com/$CHANNEL/components/pricing/
            gsutil cp pricing-component-demo* $GCS_PATH
            gsutil -m setmeta -r -h "Cache-Control:private, max-age=0" -h "content-type: text/javascript" $GCS_PATH*.mjs
            gsutil -m setmeta -r -h "Cache-Control:private, max-age=0" -h "content-type: text/html" $GCS_PATH*.html
            gsutil acl -r ch -u AllUsers:R $GCS_PATH

workflows:
  version: 2
  main-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - master
